# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ConfirmarChave.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfirmarChave(object):
    def setupUi(self, ConfirmarChave):
        ConfirmarChave.setObjectName("ConfirmarChave")
        ConfirmarChave.resize(400, 300)
        self.label = QtWidgets.QLabel(ConfirmarChave)
        self.label.setGeometry(QtCore.QRect(140, 40, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.receber_chave = QtWidgets.QLineEdit(ConfirmarChave)
        self.receber_chave.setGeometry(QtCore.QRect(20, 120, 361, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.receber_chave.setFont(font)
        self.receber_chave.setObjectName("receber_chave")
        self.btn_confi = QtWidgets.QPushButton(ConfirmarChave)
        self.btn_confi.setGeometry(QtCore.QRect(60, 220, 101, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(15, 1, 167))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 1, 167))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.btn_confi.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_confi.setFont(font)
        self.btn_confi.setObjectName("btn_confi")
        self.btn_cancel = QtWidgets.QPushButton(ConfirmarChave)
        self.btn_cancel.setGeometry(QtCore.QRect(250, 220, 101, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.btn_cancel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_cancel.setFont(font)
        self.btn_cancel.setObjectName("btn_cancel")

        self.retranslateUi(ConfirmarChave)
        QtCore.QMetaObject.connectSlotsByName(ConfirmarChave)

    def retranslateUi(self, ConfirmarChave):
        _translate = QtCore.QCoreApplication.translate
        ConfirmarChave.setWindowTitle(_translate("ConfirmarChave", "Form"))
        self.label.setText(_translate("ConfirmarChave", "Celular"))
        self.btn_confi.setText(_translate("ConfirmarChave", "Confirmar"))
        self.btn_cancel.setText(_translate("ConfirmarChave", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ConfirmarChave = QtWidgets.QWidget()
    ui = Ui_ConfirmarChave()
    ui.setupUi(ConfirmarChave)
    ConfirmarChave.show()
    sys.exit(app.exec_())
