# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ConfirmarTransf.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Confirmar_tr(object):
    def setupUi(self, Confirmar_dep):
        Confirmar_dep.setObjectName("Confirmar_dep")
        Confirmar_dep.resize(500, 400)
        self.label_titular = QtWidgets.QLabel(Confirmar_dep)
        self.label_titular.setGeometry(QtCore.QRect(20, 70, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_titular.setFont(font)
        self.label_titular.setObjectName("label_titular")
        self.label_agencia = QtWidgets.QLabel(Confirmar_dep)
        self.label_agencia.setGeometry(QtCore.QRect(20, 140, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_agencia.setFont(font)
        self.label_agencia.setObjectName("label_agencia")
        self.label_conta = QtWidgets.QLabel(Confirmar_dep)
        self.label_conta.setGeometry(QtCore.QRect(20, 210, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_conta.setFont(font)
        self.label_conta.setObjectName("label_conta")
        self.preencher_titular = QtWidgets.QLabel(Confirmar_dep)
        self.preencher_titular.setGeometry(QtCore.QRect(170, 70, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.preencher_titular.setFont(font)
        self.preencher_titular.setObjectName("preencher_titular")
        self.preencher_agencia = QtWidgets.QLabel(Confirmar_dep)
        self.preencher_agencia.setGeometry(QtCore.QRect(170, 140, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.preencher_agencia.setFont(font)
        self.preencher_agencia.setObjectName("preencher_agencia")
        self.preencher_conta = QtWidgets.QLabel(Confirmar_dep)
        self.preencher_conta.setGeometry(QtCore.QRect(170, 210, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.preencher_conta.setFont(font)
        self.preencher_conta.setObjectName("preencher_conta")
        self.btn_conf = QtWidgets.QPushButton(Confirmar_dep)
        self.btn_conf.setGeometry(QtCore.QRect(64, 310, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_conf.setFont(font)
        self.btn_conf.setObjectName("btn_conf")
        self.btn_voltar = QtWidgets.QPushButton(Confirmar_dep)
        self.btn_voltar.setGeometry(QtCore.QRect(320, 310, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_voltar.setFont(font)
        self.btn_voltar.setObjectName("btn_voltar")

        self.retranslateUi(Confirmar_dep)
        QtCore.QMetaObject.connectSlotsByName(Confirmar_dep)

    def retranslateUi(self, Confirmar_dep):
        _translate = QtCore.QCoreApplication.translate
        Confirmar_dep.setWindowTitle(_translate("Confirmar_dep", "Form"))
        self.label_titular.setText(_translate("Confirmar_dep", "Titular:"))
        self.label_agencia.setText(_translate("Confirmar_dep", "Agência:"))
        self.label_conta.setText(_translate("Confirmar_dep", "Conta:"))
        self.preencher_titular.setText(_translate("Confirmar_dep", "TextLabel"))
        self.preencher_agencia.setText(_translate("Confirmar_dep", "TextLabel"))
        self.preencher_conta.setText(_translate("Confirmar_dep", "TextLabel"))
        self.btn_conf.setText(_translate("Confirmar_dep", "Confirmar"))
        self.btn_voltar.setText(_translate("Confirmar_dep", "Voltar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Confirmar_dep = QtWidgets.QWidget()
    ui = Ui_Confirmar_tr()
    ui.setupUi(Confirmar_dep)
    Confirmar_dep.show()
    sys.exit(app.exec_())
