# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PixBeneficiario.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 400)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(110, 20, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.chave_ben = QtWidgets.QLineEdit(Form)
        self.chave_ben.setGeometry(QtCore.QRect(20, 70, 471, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.chave_ben.setFont(font)
        self.chave_ben.setObjectName("chave_ben")
        self.btn_conf = QtWidgets.QPushButton(Form)
        self.btn_conf.setGeometry(QtCore.QRect(60, 310, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_conf.setFont(font)
        self.btn_conf.setObjectName("btn_conf")
        self.btn_cancel = QtWidgets.QPushButton(Form)
        self.btn_cancel.setGeometry(QtCore.QRect(330, 310, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_cancel.setFont(font)
        self.btn_cancel.setObjectName("btn_cancel")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(160, 150, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.valor = QtWidgets.QLineEdit(Form)
        self.valor.setGeometry(QtCore.QRect(20, 210, 471, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.valor.setFont(font)
        self.valor.setObjectName("valor")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Digite a chave PIX"))
        self.btn_conf.setText(_translate("Form", "Confirmar"))
        self.btn_cancel.setText(_translate("Form", "Cancelar"))
        self.label_2.setText(_translate("Form", "Digite o valor"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
