# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VerSaldo.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VerSaldo(object):
    def setupUi(self, VerSaldo):
        VerSaldo.setObjectName("VerSaldo")
        VerSaldo.resize(400, 300)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 138, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 138, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        VerSaldo.setPalette(palette)
        self.txt_seu_saldo = QtWidgets.QLabel(VerSaldo)
        self.txt_seu_saldo.setGeometry(QtCore.QRect(50, 40, 311, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txt_seu_saldo.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(34)
        self.txt_seu_saldo.setFont(font)
        self.txt_seu_saldo.setObjectName("txt_seu_saldo")
        self.txt_saldo = QtWidgets.QLabel(VerSaldo)
        self.txt_saldo.setGeometry(QtCore.QRect(80, 140, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(32)
        self.txt_saldo.setFont(font)
        self.txt_saldo.setObjectName("txt_saldo")
        self.pushButton = QtWidgets.QPushButton(VerSaldo)
        self.pushButton.setGeometry(QtCore.QRect(140, 220, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(VerSaldo)
        QtCore.QMetaObject.connectSlotsByName(VerSaldo)

    def retranslateUi(self, VerSaldo):
        _translate = QtCore.QCoreApplication.translate
        VerSaldo.setWindowTitle(_translate("VerSaldo", "Form"))
        self.txt_seu_saldo.setText(_translate("VerSaldo", "Seu saldo é de:"))
        self.txt_saldo.setText(_translate("VerSaldo", "R$ 150094.00"))
        self.pushButton.setText(_translate("VerSaldo", "Voltar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VerSaldo = QtWidgets.QWidget()
    ui = Ui_VerSaldo()
    ui.setupUi(VerSaldo)
    VerSaldo.show()
    sys.exit(app.exec_())
