# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_sacar_diferente.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_valor_diff(object):
    def setupUi(self, valor_diff):
        valor_diff.setObjectName("valor_diff")
        valor_diff.resize(400, 300)
        self.label_valor = QtWidgets.QLabel(valor_diff)
        self.label_valor.setGeometry(QtCore.QRect(160, 30, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_valor.setFont(font)
        self.label_valor.setObjectName("label_valor")
        self.txt_valor = QtWidgets.QLineEdit(valor_diff)
        self.txt_valor.setGeometry(QtCore.QRect(50, 110, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_valor.setFont(font)
        self.txt_valor.setObjectName("txt_valor")
        self.btn_confirmar = QtWidgets.QPushButton(valor_diff)
        self.btn_confirmar.setGeometry(QtCore.QRect(34, 220, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn_confirmar.setFont(font)
        self.btn_confirmar.setObjectName("btn_confirmar")
        self.btn_cancelar = QtWidgets.QPushButton(valor_diff)
        self.btn_cancelar.setGeometry(QtCore.QRect(240, 220, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn_cancelar.setFont(font)
        self.btn_cancelar.setObjectName("btn_cancelar")

        self.retranslateUi(valor_diff)
        QtCore.QMetaObject.connectSlotsByName(valor_diff)

    def retranslateUi(self, valor_diff):
        _translate = QtCore.QCoreApplication.translate
        valor_diff.setWindowTitle(_translate("valor_diff", "Form"))
        self.label_valor.setText(_translate("valor_diff", "Valor:"))
        self.btn_confirmar.setText(_translate("valor_diff", "Confirmar"))
        self.btn_cancelar.setText(_translate("valor_diff", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    valor_diff = QtWidgets.QWidget()
    ui = Ui_valor_diff()
    ui.setupUi(valor_diff)
    valor_diff.show()
    sys.exit(app.exec_())
