# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(500, 400)
        self.label_senha = QtWidgets.QLabel(Login)
        self.label_senha.setGeometry(QtCore.QRect(20, 240, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_senha.setFont(font)
        self.label_senha.setObjectName("label_senha")
        self.label_agencia = QtWidgets.QLabel(Login)
        self.label_agencia.setGeometry(QtCore.QRect(20, 100, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_agencia.setFont(font)
        self.label_agencia.setObjectName("label_agencia")
        self.label_conta = QtWidgets.QLabel(Login)
        self.label_conta.setGeometry(QtCore.QRect(20, 170, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_conta.setFont(font)
        self.label_conta.setObjectName("label_conta")
        self.label = QtWidgets.QLabel(Login)
        self.label.setGeometry(QtCore.QRect(20, 20, 461, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.txt_agencia = QtWidgets.QLineEdit(Login)
        self.txt_agencia.setGeometry(QtCore.QRect(180, 100, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_agencia.setFont(font)
        self.txt_agencia.setObjectName("txt_agencia")
        self.txt_conta = QtWidgets.QLineEdit(Login)
        self.txt_conta.setGeometry(QtCore.QRect(180, 170, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_conta.setFont(font)
        self.txt_conta.setObjectName("txt_conta")
        self.txt_senha = QtWidgets.QLineEdit(Login)
        self.txt_senha.setGeometry(QtCore.QRect(180, 240, 311, 41))
        self.txt_senha.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.txt_senha.setEchoMode(QtWidgets.QLineEdit.Password)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_senha.setFont(font)
        self.txt_senha.setObjectName("txt_senha")

        self.btn_logar = QtWidgets.QPushButton(Login)
        self.btn_logar.setGeometry(QtCore.QRect(80, 330, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn_logar.setFont(font)
        self.btn_logar.setObjectName("btn_logar")

        self.btn_voltar = QtWidgets.QPushButton("Voltar", Login)
        self.btn_voltar.setGeometry(QtCore.QRect(310, 330, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn_voltar.setFont(font)
        self.btn_voltar.setObjectName("btn_voltar")

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Form"))
        self.label_senha.setText(_translate("Login", "Senha:"))
        self.label_agencia.setText(_translate("Login", "Agência:"))
        self.label_conta.setText(_translate("Login", "Conta:"))
        self.label.setText(_translate("Login", "Digite seus dados corretamente:"))
        self.btn_logar.setText(_translate("Login", "Entrar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QWidget()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
