# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WindowTransf.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WindowTransf(object):
    def setupUi(self, WindowTransf):
        WindowTransf.setObjectName("WindowTransf")
        WindowTransf.resize(800, 600)
        self.Transf = QtWidgets.QWidget(WindowTransf)
        self.Transf.setObjectName("Transf")
        self.label_dados = QtWidgets.QLabel(self.Transf)
        self.label_dados.setGeometry(QtCore.QRect(50, 20, 701, 81))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label_dados.setFont(font)
        self.label_dados.setObjectName("label_dados")
        self.label_agencia = QtWidgets.QLabel(self.Transf)
        self.label_agencia.setGeometry(QtCore.QRect(30, 150, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_agencia.setFont(font)
        self.label_agencia.setObjectName("label_agencia")
        self.label_conta = QtWidgets.QLabel(self.Transf)
        self.label_conta.setGeometry(QtCore.QRect(30, 240, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_conta.setFont(font)
        self.label_conta.setObjectName("label_conta")
        self.label_valor = QtWidgets.QLabel(self.Transf)
        self.label_valor.setGeometry(QtCore.QRect(30, 330, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_valor.setFont(font)
        self.label_valor.setObjectName("label_valor")
        self.txt_agencia = QtWidgets.QLineEdit(self.Transf)
        self.txt_agencia.setGeometry(QtCore.QRect(200, 150, 511, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_agencia.setFont(font)
        self.txt_agencia.setObjectName("txt_agencia")
        self.txt_conta = QtWidgets.QLineEdit(self.Transf)
        self.txt_conta.setGeometry(QtCore.QRect(200, 240, 511, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_conta.setFont(font)
        self.txt_conta.setObjectName("txt_conta")
        self.txt_valor = QtWidgets.QLineEdit(self.Transf)
        self.txt_valor.setGeometry(QtCore.QRect(200, 330, 511, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_valor.setFont(font)
        self.txt_valor.setObjectName("txt_valor")
        self.btn_depositar = QtWidgets.QPushButton(self.Transf)
        self.btn_depositar.setGeometry(QtCore.QRect(140, 460, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn_depositar.setFont(font)
        self.btn_depositar.setObjectName("pushButton")
        self.btn_voltar = QtWidgets.QPushButton(self.Transf)
        self.btn_voltar.setGeometry(QtCore.QRect(500, 460, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn_voltar.setFont(font)
        self.btn_voltar.setObjectName("pushButton_2")
        WindowTransf.setCentralWidget(self.Transf)
        self.statusbar = QtWidgets.QStatusBar(WindowTransf)
        self.statusbar.setObjectName("statusbar")
        WindowTransf.setStatusBar(self.statusbar)

        self.retranslateUi(WindowTransf)
        QtCore.QMetaObject.connectSlotsByName(WindowTransf)

    def retranslateUi(self, WindowTransf):
        _translate = QtCore.QCoreApplication.translate
        WindowTransf.setWindowTitle(_translate("WindowTransf", "MainWindow"))
        self.label_dados.setText(_translate("WindowTransf", "Digite os dados da conta beneficiária"))
        self.label_agencia.setText(_translate("WindowTransf", "Agência:"))
        self.label_conta.setText(_translate("WindowTransf", "Conta:"))
        self.label_valor.setText(_translate("WindowTransf", "Valor:"))
        self.btn_depositar.setText(_translate("WindowTransf", "Transferir"))
        self.btn_voltar.setText(_translate("WindowTransf", "Voltar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WindowTransf = QtWidgets.QMainWindow()
    ui = Ui_WindowTransf()
    ui.setupUi(WindowTransf)
    WindowTransf.show()
    sys.exit(app.exec_())
