# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Window_Saque.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Saque(object):
    def setupUi(self, Saque):
        Saque.setObjectName("Saque")
        Saque.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Saque)
        self.centralwidget.setObjectName("centralwidget")
        self.txt_saque = QtWidgets.QLabel(self.centralwidget)
        self.txt_saque.setGeometry(QtCore.QRect(220, 10, 381, 71))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.txt_saque.setFont(font)
        self.txt_saque.setObjectName("txt_saque")
        self.btn_20 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_20.setGeometry(QtCore.QRect(90, 100, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_20.setFont(font)
        self.btn_20.setObjectName("btn_20")
        self.btn_50 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_50.setGeometry(QtCore.QRect(550, 100, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_50.setFont(font)
        self.btn_50.setObjectName("btn_50")
        self.btn_100 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_100.setGeometry(QtCore.QRect(90, 220, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_100.setFont(font)
        self.btn_100.setObjectName("btn_100")
        self.btn_200 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_200.setGeometry(QtCore.QRect(550, 220, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_200.setFont(font)
        self.btn_200.setObjectName("btn_200")
        self.btn_500 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_500.setGeometry(QtCore.QRect(90, 340, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_500.setFont(font)
        self.btn_500.setObjectName("btn_500")
        self.btn_outro = QtWidgets.QPushButton(self.centralwidget)
        self.btn_outro.setGeometry(QtCore.QRect(550, 340, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_outro.setFont(font)
        self.btn_outro.setObjectName("btn_outro")
        self.btn_voltar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_voltar.setGeometry(QtCore.QRect(330, 450, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_voltar.setFont(font)
        self.btn_voltar.setObjectName("btn_voltar")
        Saque.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Saque)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        Saque.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Saque)
        self.statusbar.setObjectName("statusbar")
        Saque.setStatusBar(self.statusbar)

        self.retranslateUi(Saque)
        QtCore.QMetaObject.connectSlotsByName(Saque)

    def retranslateUi(self, Saque):
        _translate = QtCore.QCoreApplication.translate
        Saque.setWindowTitle(_translate("Saque", "Saque"))
        self.txt_saque.setText(_translate("Saque", "Qual o valor do saque?"))
        self.btn_20.setText(_translate("Saque", "20,00"))
        self.btn_50.setText(_translate("Saque", "50,00"))
        self.btn_100.setText(_translate("Saque", "100,00"))
        self.btn_200.setText(_translate("Saque", "200,00"))
        self.btn_500.setText(_translate("Saque", "500,00"))
        self.btn_outro.setText(_translate("Saque", "Outro valor"))
        self.btn_voltar.setText(_translate("Saque", "Voltar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Saque = QtWidgets.QMainWindow()
    ui = Ui_Saque()
    ui.setupUi(Saque)
    Saque.show()
    sys.exit(app.exec_())
