# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WindowDep.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QPushButton


class Ui_WindowDep(object):
    def setupUi(self, WindowDep):
        WindowDep.setObjectName("WindowDep")
        WindowDep.resize(800, 600)
        self.Deposito = QtWidgets.QWidget(WindowDep)
        self.Deposito.setObjectName("Deposito")
        self.label_dados = QtWidgets.QLabel(self.Deposito)
        self.label_dados.setGeometry(QtCore.QRect(50, 20, 701, 81))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label_dados.setFont(font)
        self.label_dados.setObjectName("label_dados")
        self.label_agencia = QtWidgets.QLabel(self.Deposito)
        self.label_agencia.setGeometry(QtCore.QRect(30, 150, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_agencia.setFont(font)
        self.label_agencia.setObjectName("label_agencia")
        self.label_conta = QtWidgets.QLabel(self.Deposito)
        self.label_conta.setGeometry(QtCore.QRect(30, 240, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_conta.setFont(font)
        self.label_conta.setObjectName("label_conta")
        self.label_valor = QtWidgets.QLabel(self.Deposito)
        self.label_valor.setGeometry(QtCore.QRect(30, 330, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_valor.setFont(font)
        self.label_valor.setObjectName("label_valor")
        self.txt_agencia = QtWidgets.QLineEdit(self.Deposito)
        self.txt_agencia.setGeometry(QtCore.QRect(200, 150, 511, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_agencia.setFont(font)
        self.txt_agencia.setObjectName("txt_agencia")
        self.txt_conta = QtWidgets.QLineEdit(self.Deposito)
        self.txt_conta.setGeometry(QtCore.QRect(200, 240, 511, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_conta.setFont(font)
        self.txt_conta.setObjectName("txt_conta")
        self.txt_valor = QtWidgets.QLineEdit(self.Deposito)
        self.txt_valor.setGeometry(QtCore.QRect(200, 330, 511, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_valor.setFont(font)
        self.txt_valor.setObjectName("txt_valor")
        WindowDep.setCentralWidget(self.Deposito)
        self.Deposito_2 = QtWidgets.QMenuBar(WindowDep)
        self.Deposito_2.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.Deposito_2.setObjectName("Deposito_2")
        WindowDep.setMenuBar(self.Deposito_2)
        self.statusbar = QtWidgets.QStatusBar(WindowDep)
        self.statusbar.setObjectName("statusbar")
        WindowDep.setStatusBar(self.statusbar)

        self.btn_depositar = QtWidgets.QPushButton("Depositar", WindowDep)
        self.btn_depositar.setGeometry(QtCore.QRect(150, 470, 170, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_depositar.setFont(font)
        self.btn_depositar.setObjectName("btn_depositar")

        self.btn_voltar = QtWidgets.QPushButton("Voltar", WindowDep)
        self.btn_voltar.setGeometry(QtCore.QRect(500, 470, 170, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_voltar.setFont(font)
        self.btn_voltar.setObjectName("btn_voltar")

        self.retranslateUi(WindowDep)
        QtCore.QMetaObject.connectSlotsByName(WindowDep)

    def retranslateUi(self, WindowDep):
        _translate = QtCore.QCoreApplication.translate
        WindowDep.setWindowTitle(_translate("WindowDep", "MainWindow"))
        self.label_dados.setText(_translate("WindowDep", "Digite os dados da conta beneficiária"))
        self.label_agencia.setText(_translate("WindowDep", "Agência:"))
        self.label_conta.setText(_translate("WindowDep", "Conta:"))
        self.label_valor.setText(_translate("WindowDep", "Valor:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WindowDep = QtWidgets.QMainWindow()
    ui = Ui_WindowDep()
    ui.setupUi(WindowDep)
    WindowDep.show()
    sys.exit(app.exec_())
